Reservationテーブルの作成
nisimotoryoga/pbl_fp_matching pull request #57
Opened 2021-05-21 01:02 UTC by nisimotoryoga

## 対応issue
親issue：#9
close #10  
## issueの要約
## 実現したいこと
clientがFPの設定した予約枠を予約するにはまず空いている枠を確認できる必要がある。
FPなら誰でも良いということはないと思うので、今回は
1. FPを選択
2. 選択したFPの枠を確認
3. 好きな予約枠を選択
4. 予約確認画面を経て予約完了
という実装を行う。

このPRは、予約ができるようにテーブルを作成することが目的。

## issueに対しておおまかに何をしたか
### テーブルの生成
rails コマンドでモデルを生成後にmigrateしてテーブルを作成
### modelのアソシエーションを追記
has_many、has_oneのアソシエーション
参考：
![image](https://user-images.githubusercontent.com/42030915/119066824-9a449000-ba1b-11eb-884c-662310af179e.png)

## レビュアーに注意して見てほしいこと
- アソシエーションの書き方
- カラムの不備

2021-05-24 06:58 UTC, shinpei-noda commented on app/controllers/clients_controller.rb
> +    @reservations = @client.reservations.eager_load(:reservation_frame).order("reservation_frames.date")
where や order の中身に文字列を渡すのはなるべく避けたほうがよいです。テーブル名の補完などを Active Record に任せた方が安全だからです。
[merge](https://api.rubyonrails.org/v6.1.3.1/classes/ActiveRecord/SpawnMethods.html#method-i-merge) というメソッドがあるので使えないか検討してみてください。

2021-05-24 07:04 UTC, shinpei-noda commented on app/views/reservations/new.html.erb
> +  <dd><%= @reservation_frame.time_frame.start_at + "〜" + @reservation_frame.time_frame.end_at %></dd>
[nits] 余裕があればですが、`start_at + "〜" + end_at` は View で繰り返し書きそうな気がするので再利用可能にした方がよさそうですね。

Decorator という仕組み (デザインパターン) があり、ex_web でも使っているので調べてみると勉強になると思います。

- ex_web で使っている Decorator の Gem
  - Draper
  - ActiveDecorator

2021-05-24 07:05 UTC, shinpei-noda commented on db/migrate/20210521005112_create_reservations.rb
> +      t.references :reservation_frame, null: false, foreign_key: true
同じクライアントが同じ予約枠を確保した場合はどうなります？ 🤔

2021-05-24 07:06 UTC, shinpei-noda commented on spec/requests/reservations_spec.rb
> +RSpec.describe "Reservations", type: :model do
describe メソッドの第 1 引数にはテスト対象のクラスを指定するのが一般的です。

```suggestion
RSpec.describe Reservation, type: :model do
```

2021-05-24 07:09 UTC, shinpei-noda commented on spec/requests/reservations_spec.rb
> +
(以前は指摘しませんでしたが 🙏) subject と is_expected を使うとよりシンプルに記述できます。ぜひ調べてみてください。

```rb
subject { Reservation.new(reservation_frame_id: reservation_frame.id, client_id: client.id) }

context '...' do
  it { is_expected.to be_valid }
end
```

2021-05-24 10:57 UTC, nisimotoryoga commented on db/migrate/20210521005112_create_reservations.rb
> +      t.references :reservation_frame, null: false, foreign_key: true
できてしまいますね。
indexで組み合わせunique対応します！

2021-05-24 14:10 UTC, nisimotoryoga commented on spec/requests/reservations_spec.rb
> +
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/57/commits/aa066811a483580a6fbb9f1876fb4bdf317f6e5f

2021-05-24 14:10 UTC, nisimotoryoga commented on spec/requests/reservations_spec.rb
> +RSpec.describe "Reservations", type: :model do
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/57/commits/aa066811a483580a6fbb9f1876fb4bdf317f6e5f

2021-05-24 14:10 UTC, nisimotoryoga commented on app/controllers/clients_controller.rb
> +    @reservations = @client.reservations.eager_load(:reservation_frame).order("reservation_frames.date")
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/57/commits/b7184ccffc0b47035a5b209c3d610342b1e1c8e2

2021-05-24 14:11 UTC, nisimotoryoga commented on db/migrate/20210521005112_create_reservations.rb
> +      t.references :reservation_frame, null: false, foreign_key: true
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/57/commits/a8c1a2f0707c331e4bbb8e36c4931dd9b1f1a4ff

2021-05-24 14:11 UTC, nishimoto-ryoga commented on app/views/reservations/new.html.erb
> +  <dd><%= @reservation_frame.time_frame.start_at + "〜" + @reservation_frame.time_frame.end_at %></dd>
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/57/commits/ff37a81b46a9d79c5ce52d2fdaae481ae3c93cf8
https://github.com/nisimotoryoga/pbl_fp_matching/pull/57/commits/79ef7640cdeafb64f261046d4fffdb84d51563f2

2021-05-25 03:12 UTC, mfw-izumi-hirayama reviewed
@nisimotoryoga 
お待たせしており申し訳ないです、コメントしましたのでご確認ください！
（私の知識不足な面もあり、質問もまじってます 🙇

2021-05-25 03:12 UTC, mfw-izumi-hirayama commented on app/controllers/clients_controller.rb
> +    @reservations = @client.reservations.eager_load(:reservation_frame).merge(Reservation.order(:date))
`merge` の使い方ちゃんとわかってなくて質問なんですが、この `.merge(Reservation.order(:date))` は `.order(:date)` とは違うクエリになるんですかね？

2021-05-25 03:12 UTC, mfw-izumi-hirayama commented on app/controllers/reservations_controller.rb
> +    @reservation = Reservation.new
この予約に入るclientはログイン中の人なんですよね？
であれば `current_client.reservations.new` と書くと、そのclientの予約になります 💡 

直接かかわることではないんですが経費のプルリクテンプレートにこういう項目があって↓
> できるだけ current_user, current_office を起点にクエリを書こう

万が一にも他人のreservationを作ってしまわないようにするためにも、なるだけ `current_client` を起点にレコードを作っていくといいと思います 🙆‍♀️

2021-05-25 03:12 UTC, mfw-izumi-hirayama commented on app/controllers/reservations_controller.rb
> +    reservation.client_id = current_client.id
上↑のコメントとあわせて、ここもこんな感じで書けそうです 💡 

```suggestion
    reservation = current_client.reservations.new(reservation_params)
```

2021-05-25 03:12 UTC, mfw-izumi-hirayama commented on spec/requests/reservations_spec.rb
> +    end
これマネフォ入ってから全員に言ってるんですが、

`is_expected` は `it { is_expected }.to ...` とワンライナーで書くためだけに存在しているといっても過言ではないので、 `it` に名前つけているなら `expect(...).to ...` のように書いたほうがRSpec wayに沿ってるように思います 💡 
https://github.com/rspec/rspec-core/blob/main/lib/rspec/core/memoized_helpers.rb#L105-L106

このテストについていえば `it { is_expected }.to ` で十分テストの意図はわかる気がしました。

2021-05-25 03:52 UTC, nisimotoryoga commented on app/controllers/clients_controller.rb
> +    @reservations = @client.reservations.eager_load(:reservation_frame).merge(Reservation.order(:date))
@mfw-izumi-hirayama 
eager_loadしているのでmergeしなくても動くんですね！？
クエリもほとんど一緒っぽいので、`.order(:date)`で良さそうです。
ありがとうございます！

![image](https://user-images.githubusercontent.com/42030915/119436169-a64f8b00-bd56-11eb-9032-4370638ceaf5.png)
![image](https://user-images.githubusercontent.com/42030915/119436272-d1d27580-bd56-11eb-873f-be438ebb55c8.png)

2021-05-26 00:50 UTC, nisimotoryoga commented on spec/requests/reservations_spec.rb
> +    end
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/57/commits/db795ea3b278655937478753d518e9bfd4d42b7d

2021-05-26 00:50 UTC, nisimotoryoga commented on app/controllers/reservations_controller.rb
> +    @reservation = Reservation.new
こちらで対応しました！https://github.com/nisimotoryoga/pbl_fp_matching/pull/57/commits/5b1b20bd3b1482ef74484653d151bb2fea819049

2021-05-26 00:51 UTC, nisimotoryoga commented on app/controllers/reservations_controller.rb
> +    reservation.client_id = current_client.id
こちらで対応しました！https://github.com/nisimotoryoga/pbl_fp_matching/pull/57/commits/5b1b20bd3b1482ef74484653d151bb2fea819049

2021-05-26 00:51 UTC, nisimotoryoga commented on app/controllers/clients_controller.rb
> +    @reservations = @client.reservations.eager_load(:reservation_frame).merge(Reservation.order(:date))
こちらで対応しました！https://github.com/nisimotoryoga/pbl_fp_matching/pull/57/commits/c8a0982e9d8e387346472fcf697da529c1648ce7

2021-05-26 00:59 UTC, mfw-izumi-hirayama requested changes
@nisimotoryoga 
テストのとこ1つだけご確認ください！
（普段はCI = Continuous Integrationといってこういうテストとかのチェックを自動で実行してくれるものを使うので気づきやすいけど、無いとなかなかわからんですね 🙈 ）

あとこれは些事で特に変更不要なんですが、
このコミットメッセージの `newを定義` という言い方はメソッドを定義しているように見えるので、
`current_clientを起点にreservationを作成するよう変更` くらいがいいかなと思いました 💡  
https://github.com/nisimotoryoga/pbl_fp_matching/pull/57/commits/5b1b20bd3b1482ef74484653d151bb2fea819049

2021-05-26 00:59 UTC, mfw-izumi-hirayama commented on spec/requests/reservations_spec.rb
> +    it { is_expected.not_to be_valid }
テスト内容変わってませんか？ 👀 （ `not` がついてる

2021-05-26 01:16 UTC, nisimotoryoga commented on spec/requests/reservations_spec.rb
> +    it { is_expected.not_to be_valid }
確認不足でした。。。
ありがとうございます🙏
![image](https://user-images.githubusercontent.com/42030915/119588280-6eeee600-be0b-11eb-9216-31e46a361edb.png)

2021-05-26 01:17 UTC, nisimotoryoga commented on spec/requests/reservations_spec.rb
> +    it { is_expected.not_to be_valid }
OKです
![image](https://user-images.githubusercontent.com/42030915/119588364-9cd42a80-be0b-11eb-9375-a47084f4f843.png)

2021-05-26 01:30 UTC, mfw-izumi-hirayama approved these changes
@nisimotoryoga 
LGTM！
野田さんからもapproveもらってください 🙏

2021-05-26 04:16 UTC, shinpei-noda approved these changes
![](https://stickershop.line-scdn.net/stickershop/v1/sticker/381169766/android/sticker.png#9o5s280cd5g)

2021-05-26 04:45 UTC, merged