クライアント側で予約キャンセルとステータスの表示に対応
nisimotoryoga/pbl_fp_matching pull request #63
Opened 2021-05-26 09:05 UTC by nisimotoryoga

## 対応issue
#6  
## issueの要約
現状マイページには自身の予約が表示されているが、
＋α下記要件を追加したい。
- 予約を削除できる
- 予約していたがFP側でキャンセルされたものについては「キャンセルされました」の表示
- 予約日が過去のものは実施済みのステータスにする

ユーザー情報の編集はこのPRでは対応しない
## issueに対しておおまかに何をしたか
### ①client周りのリファクタ
- 一覧表示で論理削除に対応
- ヘッダーリンクにマイページを追加
### ②planners/showの予約ステータスに応じた表示切り替え
予約されていたら(reservationにレコードが存在)予約済みと表示して予約できないようにする
![image](https://user-images.githubusercontent.com/42030915/119944675-837bdb80-bfcf-11eb-926e-69c50358aed1.png)

### ③clients/mypageの予約枠のステータスに応じた表示切り替え
reservation_frameのcanceled_atがnullではない場合、
「FPからキャンセルされました」という表示に変更しキャンセルできないようにする
![image](https://user-images.githubusercontent.com/42030915/119944483-4879a800-bfcf-11eb-99a6-f173d17918bb.png)

### ④予約キャンセル機能
(③の画像からの続き)
reservationのキャンセルは物理削除
![image](https://user-images.githubusercontent.com/42030915/119944729-98586f00-bfcf-11eb-8598-0290bc230c95.png)

## レビュアーに注意して見てほしいこと
- viewの条件分岐の書き方がきれいか
  - https://github.com/nisimotoryoga/pbl_fp_matching/pull/63/files#diff-44d055a7d2863cc4598f465375f8f9737ae1250b5ab157ec11b166e655bd8106R21-R25
  - https://github.com/nisimotoryoga/pbl_fp_matching/pull/63/files#diff-44d055a7d2863cc4598f465375f8f9737ae1250b5ab157ec11b166e655bd8106R21-R25

2021-05-28 10:33 UTC, mfw-izumi-hirayama reviewed
@nisimotoryoga 
2つ質問と、1つちょっとしたアドバイス的コメントを書かせていただきやした 🙏 

質問のとこ、私がコードを誤読してる気がするんですが、どうしてもわからなかったのでお時間あるときに教えていただけるとありがたいです 🙇

2021-05-28 10:33 UTC, mfw-izumi-hirayama commented on app/controllers/reservations_controller.rb
> +    if reservation.destroy
予約は物理削除なんですね 👀 

私の読解力不足で質問をしてしまうんですが、
ここでレコード消してるのにclient側のマイページで取得できるのってどういう仕組みを利用しているんですか？
レコード消してたら取得できない？ と思ったんですが、表示されてるので不思議で 🙇 
（私のコード読み解き力が低いせいで質問してしまって申し訳ないです……）

2021-05-28 10:33 UTC, mfw-izumi-hirayama commented on app/controllers/planners_controller.rb
> +    @reservation_frames = @planner.reservation_frames.order(:date).eager_load(:time_frame).not_canceled
あれ？ ここも `not_canceled` がついてるならキャンセル済みの予約は `/plannners/:id` には出てこなさそうだけど 🤔 
なんで出てくるんだろう、難しい（？）

2021-05-28 10:33 UTC, mfw-izumi-hirayama commented on app/views/clients/mypage.html.erb
> +        FPからキャンセルされました
「ReservationFrameのcanceled_atが空でなかったらキャンセルされていると解釈していい」という知識をviewが持ってると、なんだか詳しすぎるな〜という感があります 👀 
`ReservationFrame` に `canceled?` みたいなメソッドを作るとすっきりすると思います！ 💡

2021-05-31 00:49 UTC, nisimotoryoga commented on app/controllers/reservations_controller.rb
> +    if reservation.destroy
@mfw-izumi-hirayama 
ややこしくてすみません。。。
結論、クライアント側で予約はキャンセル(物理削除)したらどこにも表示できないです。
>表示されてるので不思議で 🙇

descriptionの③・④の画像のように表示されなくなるはずで、
表示されるとしたら意図しないものです。

2021-05-31 00:52 UTC, nisimotoryoga commented on app/controllers/planners_controller.rb
> +    @reservation_frames = @planner.reservation_frames.order(:date).eager_load(:time_frame).not_canceled
こちらもplanner側で予約枠のキャンセル(物理削除ではない)したらplanners/:idには出てこないはずです。。。

2021-05-31 02:01 UTC, nisimotoryoga commented on app/views/clients/mypage.html.erb
> +        FPからキャンセルされました
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/63/commits/75ec06f8fdbbfa5982d68da202f641963a9540a5

2021-05-31 02:20 UTC, mfw-izumi-hirayama commented on app/controllers/reservations_controller.rb
> +    if reservation.destroy
あああなるほど、すみませんPRのスクショを見間違えてました 🙇 
予約**枠**がキャンセルされた時に、**client** のマイページに出てくるのであって、
**予約**がキャンセルされた時は消滅するんですね 🙆‍♀️ 

失礼しました 💦 了解です！

2021-05-31 03:03 UTC, mfw-izumi-hirayama requested changes
@nisimotoryoga 
すみません、スクショ完全に見間違えてました 🙇 先の質問コメントはご放念ください 🙏 

1点だけコメントしました！

2021-05-31 03:03 UTC, mfw-izumi-hirayama commented on app/models/reservation_frame.rb
> +  end
キャンセル日時がnilだったらまだキャンセルされていないのでは？ 👀 

`canceled?` がtrueを返したら、普通は「キャンセル済み」ととらえられます 💡

2021-05-31 04:19 UTC, nisimotoryoga commented on app/models/reservation_frame.rb
> +  end
おっしゃる通りですね
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/63/commits/eceb3af45b2c8daba8a3617842ca52bc174ddd7e

2021-05-31 04:55 UTC, mfw-izumi-hirayama approved these changes
@nisimotoryoga 
LGTMです！！👍 良い感じ！

見間違え、大変失礼しました 🙇 💦

2021-06-01 01:13 UTC, shinpei-noda commented on app/models/reservation_frame.rb
> +    self.canceled_at.present?
ActiveRecord が `{カラム名}?` という名前の predicate method を自動定義してくれます。

```suggestion
    canceled_at?
```

2021-06-01 01:13 UTC, shinpei-noda commented on app/views/clients/mypage.html.erb
> +        <%= link_to  "キャンセル", reservation_path(reservation), method: :delete %>
[nits] NodaCop

```suggestion
        <%= link_to "キャンセル", reservation_path(reservation), method: :delete %>
```

2021-06-01 01:14 UTC, shinpei-noda approved these changes
細かいコメントだけしています。

![](https://stickershop.line-scdn.net/stickershop/v1/sticker/382105100/android/sticker.png)

2021-06-01 01:18 UTC, nisimotoryoga commented on app/views/clients/mypage.html.erb
> +        <%= link_to  "キャンセル", reservation_path(reservation), method: :delete %>
Oh...
ありがとうございます！
このPRの後にリファクタPRあげます🙇‍♂️

2021-06-01 01:19 UTC, nisimotoryoga commented on app/models/reservation_frame.rb
> +    self.canceled_at.present?
そんなに省略しちゃえるんですね。
ありがとうございます！

2021-06-01 01:19 UTC, merged