ユーザー名を編集できる
nisimotoryoga/pbl_fp_matching pull request #69
Opened 2021-05-31 02:35 UTC by nisimotoryoga

## 対応issue
close #64 
## issueの要約
非同期ではなく編集ページ作って対応する
clientとplannerの両方を対応する

イメージ
①mypageでnameの横に編集ボタンがある
②編集ボタンを押すと編集画面に遷移
③編集後、保存ができればマイページに遷移
(できなければそのまま編集ページにレンダー)

## issueに対しておおまかに何をしたか
## レビュアーに注意して見てほしいこと

2021-05-31 06:13 UTC, mfw-izumi-hirayama approved these changes
@nisimotoryoga 
LGTM 👍 ✨

2021-06-01 01:17 UTC, shinpei-noda commented on app/controllers/clients_controller.rb
> +    end
インスタンス変数のスコープは可能な限り狭めたいです。`redirect_to` の場合は必要ないはずですので。

```suggestion
    if current_client.update(client_params)
      flash[:success] = "編集しました。"
      redirect_to mypage_clients_path
    else
      flash.now[:danger] = "編集に失敗しました。"
      @client = current_client
      render :edit
    end
```

2021-06-01 01:18 UTC, shinpei-noda requested changes
コメントしました。

2021-06-01 02:03 UTC, nisimotoryoga commented on app/controllers/clients_controller.rb
> +    end
勉強になります！
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/69/commits/f161ba4b9abcb44f05db20ba6e15a9482ee1f72f

2021-06-02 04:48 UTC, shinpei-noda approved these changes
![](https://stickershop.line-scdn.net/stickershop/v1/sticker/386889167/android/sticker.png#ukcn2q8k0d)

2021-06-02 05:13 UTC, merged