デプロイ後のバグ・リファクタ対応
nisimotoryoga/pbl_fp_matching pull request #75
Opened 2021-06-07 08:18 UTC by nisimotoryoga

## 対応issue
close #66
## issueの要約
## issueに対しておおまかに何をしたか
## レビュアーに注意して見てほしいこと

2021-06-07 08:59 UTC, shinpei-noda commented
@nisimotoryoga バグとリファクタリングの項目ごとに issue を起票して PR も分けてほしかった気持ちがあります。1 PR で複数の事柄が含まれているとレビュアーが混乱してしまいますし、のちのち見たときのことを考えても issue を分割しておいた方が理解しやすいと思いますので。

2021-06-07 09:20 UTC, nisimotoryoga commented
@shinpei-noda 
PR分けるとそれはそれで見るのが大変かと思い一緒にしてしまいました。
発表まで時間もないので悩ましかったのですが、分けた方が良さそうですかね💦
分けた方が早く確認できそうとかであれば分けます🙇‍♂️

2021-06-07 09:37 UTC, shinpei-noda commented on app/controllers/application_controller.rb
> +    return unless request.path.in?(['/clients/sign_up', '/clients/sign_in']) && planner_signed_in?
ApplicationController は階層的に一番上に存在するコントローラなのですが、その中で `/clients/sign_up` や `/clients/sign_in` という知識があるのは NG です。

この知識を必要とする具体的なコントローラは `/clients/sign_up` や `/clients/sign_in` なので、そこで判定するようにしましょう。

2021-06-07 09:48 UTC, shinpei-noda requested changes

2021-06-07 09:48 UTC, shinpei-noda commented on app/models/client.rb
> +  validates :name, presence: true, length: { maximum: 10, message: '10文字以内です' }, chars_must_be_less_than4bytes: true
おー、EachValidator の活用いいですね 👍

2021-06-07 09:48 UTC, shinpei-noda commented on app/models/reservation_frame.rb
>      return unless date.wday == 6 && !time_frame_id.between?(3, 11)
既存の部分ですいません。
unless 式の条件説に && や || や ! を使うと、人間の脳みそでは辛いものがあります。
以下のテクニックを参考に、条件を解きほぐしてみてください。

[ド・モルガンの法則でunlessのややこしい条件をifに読み替えよう - Qiita](https://qiita.com/jnchito/items/a24e2b188e44c0f8c2ad)

2021-06-07 09:48 UTC, shinpei-noda commented on app/validators/chars_must_be_less_than4bytes_validator.rb
> +    unavailable_chars = value.scan(/[^\u0000-\uFFFF]/)
ただしくは  \uD800-\uDFFF は 2 バイトですね (サロゲート) 。ただ UTF-8 の世界では上記正規表現でも問題はないですが、なんとなく気持ち悪さはあります。

参考: [サロゲートペア入門](https://codezine.jp/article/detail/1592)

2021-06-07 09:52 UTC, shinpei-noda commented on app/validators/chars_must_be_less_than4bytes_validator.rb
> +    unavailable_chars = value.scan(/[^\u0000-\uFFFF]/)
正確には `/[^\u0000-\uD7FF\uE000-\uFFFF]/` ですね。\uD800-\uDFFF は UTF-16 のサロゲートペアに用いるための文字の領域ですね。Unicode では使われていません。

```
"\u{D800}" # invalid Unicode codepoint
```

2021-06-07 10:29 UTC, mfw-izumi-hirayama commented
@nisimotoryoga 
良い感じなのではと思います〜 🙌 
野田さんがレビュー中のようですのでapproveは押さないでおきますね、野田さんからOK出たらマージしちゃってよいと思います！

issueは1つでいいかもですがPRは分けたほうが親切でしたね 👀
（まあこういうのは今やってるのが個人の課題開発だから起こる話であって、実際はissueがまず切られてアサインされるという流れなのであまり気にしなくてもいいかもですね 🙆‍♀️ ）

2021-06-07 23:18 UTC, nisimotoryoga commented on app/models/reservation_frame.rb
>      return unless date.wday == 6 && !time_frame_id.between?(3, 11)
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/75/commits/11c63fa3f908cb228ce1ab839c0f837844950016

2021-06-07 23:18 UTC, nisimotoryoga commented on app/controllers/application_controller.rb
> +    return unless request.path.in?(['/clients/sign_up', '/clients/sign_in']) && planner_signed_in?
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/75/commits/be50bd2357c95103f73f7d3ac95ad5079ccd0aa5
https://github.com/nisimotoryoga/pbl_fp_matching/pull/75/commits/0b8b621cdb1858519dbbc8a77728db243065baa0

2021-06-07 23:19 UTC, nisimotoryoga commented on app/validators/chars_must_be_less_than4bytes_validator.rb
> +    unavailable_chars = value.scan(/[^\u0000-\uFFFF]/)
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/75/commits/a9533cfc91819357519359d1d5e9cdf012687918

2021-06-08 01:25 UTC, shinpei-noda commented on app/controllers/clients/omniauth_callbacks_controller.rb
> +  # end
コードをコメントで残すのはやめましょう。あるいは、コメントを残すためのなにか特別な理由がある場合はそれをコメントしてください。

2021-06-08 01:27 UTC, shinpei-noda commented
@nisimotoryoga 肝心な点を見落としていました 💦 
各種バリデーションの単体テストがないので、モデルやバリデータのテストを実装してください。

2021-06-08 03:42 UTC, nisimotoryoga commented
@shinpei-noda 
>各種バリデーションの単体テストがないので、モデルやバリデータのテストを実装してください。

すみません、やってみます！
PR分けた方が良いですかね？

2021-06-08 08:10 UTC, nisimotoryoga commented on app/controllers/clients/omniauth_callbacks_controller.rb
> +  # end
自動生成ファイルもコードコメント削除するようにします🙇‍♂️

2021-06-08 09:23 UTC, nishimoto-ryoga commented
こちらの対応は別PRで行うためマージする。
https://github.com/nisimotoryoga/pbl_fp_matching/pull/75#issuecomment-856369774

slackのやり取り：https://moneyforward.slack.com/archives/C020CDQQDPB/p1623140077133300

2021-06-08 09:24 UTC, merged