:up:time_frame_idではなくstart_atを利用
nisimotoryoga/pbl_fp_matching pull request #78
Opened 2021-06-09 02:24 UTC by nisimotoryoga

## 対応issue
close #77 
## issueの要約

## issueに対しておおまかに何をしたか
## レビュアーに注意して見てほしいこと

2021-06-09 02:43 UTC, mfw-izumi-hirayama requested changes
@nisimotoryoga 
コメントしました！

2021-06-09 02:43 UTC, mfw-izumi-hirayama commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.between?('11:00', '14:30')
あー、たしかにIDでの比較はそもそもよくなかったですね 🙇 申し訳ない

この `between?` なんですが、

```
[14] pry(main)> '11:00'.between?('11:00', '14:30')
=> true
[15] pry(main)> '11:00'.between?('9:00', '14:30')
=> false
```

てな感じで時刻ではなく文字列として辞書順に比較してると思うので、
今のコードが正しく動いているのはたまたま範囲がどちらも `1` から始まっていてかつ比較される時刻の文字列が `0` または `1` から始まっているからですね。

時刻（DateTime）に変換して比較するのがいいと思います。
日付はこの際なんでもいいと思うので比較対象を両方とも時刻に変換するとかですかね 💭 
https://apidock.com/rails/String/to_time

2021-06-09 05:16 UTC, nisimotoryoga commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.between?('11:00', '14:30')
@mfw-izumi-hirayama 
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/78/commits/21f086941f856c3225de8b46ca21e0cf0110f32d

2021-06-09 06:12 UTC, mfw-izumi-hirayama approved these changes
@nisimotoryoga 
ひとつコメントしましたが動くならいいように思いました、LGTM 👍

2021-06-09 06:12 UTC, mfw-izumi-hirayama commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.to_datetime.between?('11:00', '14:30')
へーーーこれで良い感じに動くんですね 👀 
datetimeとstringの比較になってるので、そろえたほうが良いと思います。（予期せぬ結果になったりすることがあるので）

2021-06-09 11:11 UTC, shinpei-noda commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.to_datetime.between?('11:00', '14:30')
文字列の比較だと厳密ではない (辞書順でたまたま動いているだけ) なので、Time (DateTime) での比較がベストだと思います！

2021-06-09 11:13 UTC, shinpei-noda commented
> clearDBの仕様でidは10飛ばしになってしまう。

なんという仕様 😇

2021-06-09 23:32 UTC, nisimotoryoga commented
> > clearDBの仕様でidは10飛ばしになってしまう。
> 
> なんという仕様 😇

circular replicationというのを使っている関係でキーが衝突しないようにするためだそうです。

![image](https://user-images.githubusercontent.com/42030915/121442083-e0ab6000-c9c5-11eb-9aac-6f299c24f39e.png)
https://w2.cleardb.net/faqs/#general_16

2021-06-10 00:16 UTC, nisimotoryoga commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.to_datetime.between?('11:00', '14:30')
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/78/commits/1d19bb3266dbc927a0649561e24c05b4c9ebaa39

2021-06-10 01:56 UTC, shinpei-noda commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.to_datetime.between?(DateTime.parse('11:00'), DateTime.parse('14:30'))
start_at  が 2021/06/10 (木) 12:00 JST だとして、これ 2021/06/10 (木) の部分をレシーバと実引数で統一しないと比較できないと思います。

2021-06-10 01:58 UTC, shinpei-noda commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.to_datetime.between?(DateTime.parse('11:00'), DateTime.parse('14:30'))
あ、start_at は文字列なので、to_datetime した際の日付になるのか。
うーん、ただいずれにせよ (現実的にはありえないが) 

1. to_datetime
2. DateTime.parse('11:00')
3. DateTime.parse('14:30')

1 と 2 のタイミングで日付をまたいだとしたら結果が変わってしまいますよね。

2021-06-10 02:00 UTC, nisimotoryoga commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.to_datetime.between?(DateTime.parse('11:00'), DateTime.parse('14:30'))
![image](https://user-images.githubusercontent.com/42030915/121452809-0abb4d00-c9db-11eb-9fc0-6df0718fed7b.png)

2021-06-10 02:00 UTC, nisimotoryoga commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.to_datetime.between?(DateTime.parse('11:00'), DateTime.parse('14:30'))
ここで確認してOKそうと思ったんですが、
>1 と 2 のタイミングで日付をまたいだとしたら結果が変わってしまいますよね。

これは確かにそうですね。

2021-06-10 02:09 UTC, nisimotoryoga commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.to_datetime.between?(DateTime.parse('11:00'), DateTime.parse('14:30'))
@shinpei-noda 
上記ケースだとfalseが出るので、バリデーションにかかるので不整合が起こらないのと、
かなりレアケースな気がするので今回はパスしたいなと思っているのですがいかがでしょうか。
![image](https://user-images.githubusercontent.com/42030915/121453481-3559d580-c9dc-11eb-964a-4a6ee7fc777d.png)

2021-06-10 02:15 UTC, shinpei-noda commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.to_datetime.between?(DateTime.parse('11:00'), DateTime.parse('14:30'))
これはプログラマ的な僕の主観ですが、実行タイミングに依存して理論上正しく動かないケースがある (たとえそれが 0.000000001% だとしても) のは許容しづらいなと思っています。

2021-06-10 02:16 UTC, shinpei-noda commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.to_datetime.between?(DateTime.parse('11:00'), DateTime.parse('14:30'))
時間の文字列 ("時間:分") を厳密に比較する専用のクラスを作ってみるのはどうでしょうか？

2021-06-10 02:17 UTC, mfw-izumi-hirayama commented on app/models/reservation_frame.rb
> +    return if time_frame.start_at.to_datetime.between?(DateTime.parse('11:00'), DateTime.parse('14:30'))
@shinpei-noda @nisimotoryoga 
実際

```
time_frame.start_at.to_datetime.between?('11:00', '14:30')
```

で意図したとおりにDateTimeの比較が行われることがわかったので、これ 👆 が一番良いと思います 👀 
https://api.rubyonrails.org/classes/DateTime.html#method-i-3C-3D-3E

2021-06-10 05:48 UTC, mfw-izumi-hirayama reviewed
@nisimotoryoga 
Slackで書いたとおり専用クラスを作ること自体私はネガティブな意見がありますが、
ひとまず作る前提でレビューしました！ 研修修了まであとすこしですね 💪

2021-06-10 05:48 UTC, mfw-izumi-hirayama commented on app/common_class/compare_time.rb
> +    today_str = Time.zone.today
`_str` とついていたらstringクラスのインスタンスを想像してしまいます 🙈 
代入されている値のclassにあわせて変数名を再考してみてください！
（個人的には `today` でいいんじゃと思います）

2021-06-10 05:48 UTC, mfw-izumi-hirayama commented on app/common_class/compare_time.rb
> +class CompareTime
こういうRailsのデフォルトに無い存在の命名難しいですが `TimeComparator` とか `TimeComparation` とか名詞にしたほうがいいかなと思います。

あとはこれ状態を持たない関数的な処理なので、インスタンス作る必要ないように思いました。
（※わからない言葉あったらきいてください 🙇 ）
クラスメソッドとして `compare` （あるいは `call` とか `execute` とかでも）を実装するのはいかがでしょう 👀

2021-06-10 05:48 UTC, mfw-izumi-hirayama commented on app/models/reservation_frame.rb
> +    compare_time = CompareTime.new
変数は使う直前に作りましょう 💨 
土曜じゃなければこの変数使いませんよね 🚿

2021-06-10 05:50 UTC, shinpei-noda commented on app/models/reservation_frame.rb
> +    return if compare_time.compare(time_frame)
CompareTime というのは動詞になっているので、命名として不適切かなと思います。クラスは基本的には「もの」を表すので名詞です。ただし、サービスクラスと言って特定のビジネスロジックをクラスとして表現する場合もあるので、その限りではありません。ただ今回はまず「比較可能な時間」をもととして考えてみましょう。たとえば TimeString という時間文字列用のクラスを作ってみるのはどうでしょう？

```rb
class TimeString
  def initialize(time_str)
    @time_str = time_str
  end

  # 何かしらを実装する
end
```

そして時間文字列オブジェクトを整数オブジェクトのように自然に比較できるようにします。time_str1 > time_str2 のような感じですね。

これは https://docs.ruby-lang.org/ja/latest/class/Comparable.html を使えば実現できます。

上記のヒントを元に考えてみてください。

2021-06-10 09:01 UTC, nisimotoryoga commented on app/models/reservation_frame.rb
> +    return if compare_time.compare(time_frame)
@shinpei-noda 
> ```
> [14] pry(main)> '11:00'.between?('11:00', '14:30')
> => true
> [15] pry(main)> '11:00'.between?('9:00', '14:30')
> => false
> ```
> 
> てな感じで時刻ではなく文字列として辞書順に比較してると思うので、
> 今のコードが正しく動いているのはたまたま範囲がどちらも `1` から始まっていてかつ比較される時刻の文字列が `0` または `1` から始まっているからですね。
> 

module Comparableで修正してみましたが、
平山さんご指摘の部分を解決できないという認識であってますか？
書き方が違うとかであれば教えていただけますと🙏

2021-06-10 09:03 UTC, nisimotoryoga commented on app/models/reservation_frame.rb
> +    return if compare_time.compare(time_frame)
>class TimeString
  include Comparable

  def self.compare(time_str)
    time_str.between?('9:00', '15:00')
  end
end

![image](https://user-images.githubusercontent.com/42030915/121497224-2e4fb900-ca16-11eb-906d-24ca7b3e9cff.png)

2021-06-10 14:16 UTC, shinpei-noda commented on app/models/reservation_frame.rb
> +    return if compare_time.compare(time_frame)
おっと、こういうイメージでした！

```rb
class TimeString
   include Comparable

  def initialize(time_str)
    @time_str = time_str
  end

  def hour
    # @time_str から時間の整数を計算。
  end

  def minute
    # @time_str から分の整数を計算。
  end

  def <=>(other)
    # other には別の TimeString オブジェクトが渡されるので比較するロジックを実装する。
    # このメソッドの返り値については https://docs.ruby-lang.org/ja/latest/class/Comparable.html の上部を参照。
  end
end

```rb
TimeString.new('11:00') >= TImeString.new('10:59') #=> true
TimeString.new('11:00') >= TImeString.new('11:00') #=> true
TimeString.new('11:00') >= TImeString.new('11:01') #=> false
TimeString.new('11:00') > TImeString.new('11:00') #=> false
```

というイメージでした！

2021-06-14 01:50 UTC, nisimotoryoga commented on app/models/reservation_frame.rb
> +    return if compare_time.compare(time_frame)
ありがとうございます！
こちらで対応しました！
https://github.com/nisimotoryoga/pbl_fp_matching/pull/78/commits/5a50dcb6fdcb500db41f5f2df327d03f2f69a61f

2022-01-06 10:19 UTC, closed without merging