バリデーションに関するRSpec
nisimotoryoga/pbl_fp_matching pull request #79
Opened 2021-06-09 07:41 UTC by nisimotoryoga

## 対応issue
close #76 
## issueの要約
バリデーションに関する単体テストを追加
## issueに対しておおまかに何をしたか
### テスト対応したバリデーション
- 名前が10文字以上
- 名前に絵文字を含む
- 
## レビュアーに注意して見てほしいこと

2021-06-17 00:34 UTC, mfw-izumi-hirayama requested changes
@nisimotoryoga 
`type: :request` と `type: :model` がごっちゃになっているっぽいので、調べて適切なtypeを指定しましょう〜！
ファイルの置き場所も変わってきますので、そこも変えといてください 💡 

https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec
https://relishapp.com/rspec/rspec-rails/v/5-0/docs/model-specs

2021-06-17 00:34 UTC, mfw-izumi-hirayama commented on spec/factories/reservation_frame.rb
> +    date        { Time.zone.now.to_date + 8 - Time.zone.now.to_date.wday }
[imo]
個人的にはスペースで見た目をそろえるのは反対派です  💭 
理由は、たとえばこのクラスに `jugemujugemgokounosurikire` のような長い名前のアトリビュートが足された時、
中身が変わってないのに周囲の全ての行でスペースを追加するはめになり、追加の作業が生まれる＆プルリクの余計なdiffが生まれるためです。

OSSのコードを読んでいるとそろっているものもあるんですが、やめたほうがいいんではと思ってます。

2021-06-17 00:34 UTC, mfw-izumi-hirayama commented on spec/factories/time_frames.rb
> +  factory :time_frame1, class: TimeFrame do
この `1` とか `2` とかをプログラマが覚えておかないといけないのはあまり好ましくないように思います 👀 
「1なら動くけど2では動かないテストがある」ようなことが起きて、その区別はテスト対象の事情である（= 10時だと良いけど11時だと駄目という実装をしているのはTimeFrameではなくそれを使うテスト対象のクラスのはず）なのに、そのテストを理解するためにここを見に来ないといけなくなります。
10時とか11時とかの区別が必要であるなら、それはFactoryではなく、Factoryを使うテスト側で設定しましょう💡 
つまりFactoryで入れる値はなんでもいいようにして、値がなんでもよくない時はテスト側で設定します。

というわけでFactoryは1つだけにしましょう 🚿 
start_atとend_atはなんでもいいので、↓のどちらかかなと思います
- とりあえず10時〜10時半を入れておく
- start_atをランダムに設定して、end_atはそれに30分足したものとする

2021-06-17 00:34 UTC, mfw-izumi-hirayama commented on spec/requests/reservation_frames_spec.rb
> +        date: next_mon,
このテスト、

>date, time_frame_id, planner_id がすべて設定されている場合
>reservation_frameが有効

という内容のようですが、曜日関係あります？
わざわざ曜日を設定してあると、テスト内容に曜日が関係あるかのように見えてしまいます 👀 

曜日を気にしない `date` を作るか、特段再利用していないようなので直接 `date: Date.current` みたいに入れてしまってもいいと思います。

2021-06-17 00:34 UTC, mfw-izumi-hirayama commented on spec/requests/reservation_frames_spec.rb
> +  context 'dateが土曜日10:00の場合' do
曜日が関係してくるのはこれ以降ですかね 💭 
 `let(!)` で定義するのはできるだけ使う場所だけにしましょう〜

変数のスコープをせばめるのとあわせて1つくらいネストさせてもいいかも。
`describe '土曜日はみじかい'` とか `context '土曜日のとき'` みたいな階層をひとつ足して、
土曜日のテストをしている既存のcontextはその階層の下に置く、というのはどうでしょう 💡

2021-06-17 01:50 UTC, shinpei-noda commented on spec/requests/clients_spec.rb
> +    end
このテストだと仕様が網羅されておらず、名前が 10 文字未満の場合は valid なのか invalid なのか不明なので、valid なケースも追加するとよいです 🙌

2021-06-17 01:50 UTC, shinpei-noda commented on spec/requests/reservation_frames_spec.rb
>        )
```rb
reservation_frame = ReservationFrame.new(        
  date: Time.zone.now.to_date - 1,
  time_frame_id: time_frame1.id, 
  planner_id: planner.id 
)
```

ここは繰り返しになっているので let を使って DRY にできそうです。
各 context では変化しうる値 (今回は date, time_frame_id, time_frame_id) だけを let で指定するようにすると読みやすいテストコードになります。

2021-06-17 03:40 UTC, nisimotoryoga commented on spec/requests/reservation_frames_spec.rb
> +        date: next_mon,
@mfw-izumi-hirayama 
月曜である必要はないんですが、土日を避けたいと言うのはありました。
(土日だとバリデーションに引っかかるため)

>date: Date.current 

これだと土日にテストした際に通らないなと思いまして。

上記理由だといかがでしょうか？

2021-06-17 03:48 UTC, mfw-izumi-hirayama commented on spec/requests/reservation_frames_spec.rb
> +        date: next_mon,
@nisimotoryoga 
あーなるほど！ 💡 
土日だと通らないテストなら、 `context '月〜金のとき'` という階層にしましょうか。

2021-06-18 08:13 UTC, mfw-izumi-hirayama reviewed
@nisimotoryoga 
野田さんのコメントのとこですがイメージついてないかもと思ったので例を書いてみました 💡

2021-06-18 08:13 UTC, mfw-izumi-hirayama commented on spec/models/reservation_frame_spec.rb
> +    let!(:next_mon) { Time.zone.now.to_date + 8 - Time.zone.now.to_date.wday }
これが良い手なのか確信は無いんですが↓でてきとうな月曜日が得られるっぽいです。ちょっとはわかりやすくなるかも
（ `:monday` は省略可）

```
Date.current.beginning_of_week(:monday)
```

https://api.rubyonrails.org/v6.1.3/classes/DateAndTime/Calculations.html#method-i-beginning_of_week


そしてこの変数名ですが、名前で月曜日と言ってしまっているのは微妙な気がします。
contextでは火曜でも水曜でもいいはずで、contextのタイトルとテストの中身が乖離しているというか。
で全曜日でコピペテストを書くのもあれなので、変数名を汎用的にしつつテストコードで「月〜金ならいつでも」と表明してみるのはいかがでしょう。
（特定の曜日で落ちるバグがあれば、「たまにテストが落ちる」ということで発覚する）

```suggestion
    let!(:weekday) { Date.current.beginning_of_week(%i[monday tuesday wednesday thursday friday].sample) }
```

直截的ではないですが関連↓
https://github.com/willnet/rspec-style-guide#factorybot%E3%81%AE%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E5%80%A4

2021-06-18 08:13 UTC, mfw-izumi-hirayama commented on spec/models/reservation_frame_spec.rb
> +  end
もとの指摘の意図はこういう感じだと思います 💡 
他のテストとか読んでみるといいかもです 👀 
```suggestion
  let!(:reservation_frame) { ReservationFrame.new(date: date, time_frame_id: time_frame.id, planner_id: planner.id) }

  context 'date が設定されていない場合' do
    let!(:date) { nil }
    it 'reservation_frameが無効' do
      expect(reservation_frame.valid?).to eq(false)
    end
  end
```

2021-06-19 14:49 UTC, nisimotoryoga commented on spec/models/reservation_frame_spec.rb
> +    let!(:next_mon) { Time.zone.now.to_date + 8 - Time.zone.now.to_date.wday }
ありがとうございます！
`beginning_of_week`知らなかったです。
過去日付はバリデーションかかっちゃうので、
似たような`next_week`を使ってみます。

2021-06-19 15:06 UTC, nisimotoryoga commented on spec/models/reservation_frame_spec.rb
> +  end
let!(:date)で上書きできるんですね！
ありがとうございます！

2022-01-06 10:19 UTC, closed without merging